language: java

services:
  - mysql
  
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS reviewit;'
  - mysql -e 'CREATE DATABASE reviewit;'
  - mysql -e 'use reviewit;'
  - mysql -u root reviewit < src/main/resources/database/review.sql;