language: java
sudo: true
jdk:
  - openjdk11

services:
  - mysql
  
before_script:
  - sudo mysql -e 'DROP DATABASE IF EXISTS reviewit;'
  - sudo mysql -e 'CREATE DATABASE reviewit;'
  - sudo mysql -e 'use reviewit;'
  - sudo mysql -u root reviewit < src/main/resources/database/review.sql;
  
before_install:
  - chmod +x mvnw